[program:blade_book]
command=/usr/local/bin/gunicorn -w 2 -b 127.0.0.1:5004 --graceful-timeout 5 --timeout 120 app:app
directory=/home/shg/blade-book
user=shg
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopsignal=TERM
stopwaitsecs=10
environment=BLADEBOOK_CONFIG_DIR="/etc/blade-book",BLADEBOOK_DATA_DIR="/var/lib/blade-book",BLADEBOOK_LOG_DIR="/var/log/blade-book",BLADEBOOK_WWW_DIR="/var/www/html/blade-book"
stdout_logfile=/var/log/blade-book/gunicorn.log
stderr_logfile=/var/log/blade-book/gunicorn_err.log
